import {
  Organization,
  User,
  Membership,
  Client,
  Invoice,
  Reminder,
  EmailEvent,
  AuditLog,
  Connection,
  AutomationSettings,
  AISettings,
  Subscription,
  Usage,
  NotificationItem,
} from '../types';

const STORAGE_KEYS = {
  CURRENT_USER: 'ic_current_user',
  CURRENT_ORG: 'ic_current_org',
  ORGS: 'ic_orgs',
  CLIENTS: 'ic_clients',
  INVOICES: 'ic_invoices',
  REMINDERS: 'ic_reminders',
  EMAIL_EVENTS: 'ic_email_events',
  AUDIT_LOGS: 'ic_audit_logs',
  CONNECTIONS: 'ic_connections',
  AUTOMATION_SETTINGS: 'ic_automation_settings',
  AI_SETTINGS: 'ic_ai_settings',
  SUBSCRIPTION: 'ic_subscription',
  USAGE: 'ic_usage',
  NOTIFICATIONS: 'ic_notifications',
  ONBOARDING_COMPLETED: 'ic_onboarding_completed',
};

export const INITIAL_USER: User = {
  id: '',
  email: '',
  name: 'User',
  avatarUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=User',
};

export const INITIAL_ORG: Organization = {
  id: '',
  name: 'My Workspace',
  slug: 'my-workspace',
  ownerUserId: '',
  timezone: 'Asia/Kolkata',
  currency: 'INR',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli_abc_interiors',
    organizationId: 'org_apex_studio',
    name: 'Rohit Sharma',
    email: 'rohit@abcinteriors.co',
    companyName: 'ABC Interiors & Architecture',
    relationshipType: 'REGULAR',
    paymentReliabilityScore: 84,
    averagePaymentDelayDays: 6.4,
    totalInvoiced: 480000,
    totalPaid: 405000,
    totalOutstanding: 75000,
    neverContact: false,
    notes: 'Key architectural client. Usually requires a polite 2nd reminder before finance releases payment.',
    createdAt: '2026-03-10T12:00:00Z',
    updatedAt: '2026-08-25T10:00:00Z',
  },
  {
    id: 'cli_zenith_media',
    organizationId: 'org_apex_studio',
    name: 'Priya Mehra',
    email: 'priya@zenithmedia.agency',
    companyName: 'Zenith Growth Media',
    relationshipType: 'VIP',
    paymentReliabilityScore: 96,
    averagePaymentDelayDays: 2.1,
    totalInvoiced: 850000,
    totalPaid: 750000,
    totalOutstanding: 100000,
    neverContact: false,
    notes: 'Long-term retainer partner. Keep communication warm and collaborative.',
    createdAt: '2026-01-15T09:00:00Z',
    updatedAt: '2026-08-20T11:00:00Z',
  },
  {
    id: 'cli_novabuild',
    organizationId: 'org_apex_studio',
    name: 'Vikram Mehta',
    email: 'vmehta@novabuild.in',
    companyName: 'NovaBuild Infra',
    relationshipType: 'LATE_PAYER',
    paymentReliabilityScore: 62,
    averagePaymentDelayDays: 14.5,
    totalInvoiced: 620000,
    totalPaid: 520000,
    totalOutstanding: 100000,
    neverContact: false,
    notes: 'Complex multi-tier internal approval. Needs direct invoice references and account numbers.',
    createdAt: '2026-04-12T14:00:00Z',
    updatedAt: '2026-08-18T16:00:00Z',
  },
  {
    id: 'cli_craft_roasters',
    organizationId: 'org_apex_studio',
    name: 'Devika Rao',
    email: 'devika@craftroasters.co',
    companyName: 'Craft Coffee Roasters',
    relationshipType: 'NEW',
    paymentReliabilityScore: 90,
    averagePaymentDelayDays: 3.0,
    totalInvoiced: 45000,
    totalPaid: 0,
    totalOutstanding: 45000,
    neverContact: false,
    notes: 'Brand identity refresh. Brand new client.',
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-28T09:00:00Z',
  },
  {
    id: 'cli_pulse_health',
    organizationId: 'org_apex_studio',
    name: 'Dr. Sameer Joshi',
    email: 's.joshi@pulsehealth.org',
    companyName: 'Pulse Digital Healthcare',
    relationshipType: 'REGULAR',
    paymentReliabilityScore: 92,
    averagePaymentDelayDays: 4.2,
    totalInvoiced: 540000,
    totalPaid: 380000,
    totalOutstanding: 160000,
    neverContact: false,
    notes: 'SaaS portal design & mobile app frontend.',
    createdAt: '2026-02-20T10:00:00Z',
    updatedAt: '2026-08-30T10:00:00Z',
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv_1042',
    organizationId: 'org_apex_studio',
    clientId: 'cli_abc_interiors',
    clientName: 'Rohit Sharma',
    clientEmail: 'rohit@abcinteriors.co',
    companyName: 'ABC Interiors & Architecture',
    invoiceNumber: 'INV-1042',
    invoiceAmount: 75000,
    currency: 'INR',
    invoiceDate: '2026-08-10',
    dueDate: '2026-08-25',
    status: 'OVERDUE',
    daysOverdue: 7,
    source: 'GMAIL',
    sourceReference: 'msg_gmail_89324798234',
    lastReminderAt: '2026-08-28T09:30:00Z',
    reminderCount: 1,
    nextReminderAt: '2026-09-02T10:00:00Z',
    isPaused: false,
    extractionConfidence: 'HIGH',
    notes: 'Commercial 3D render package phase 2.',
    createdAt: '2026-08-10T09:00:00Z',
    updatedAt: '2026-08-28T09:30:00Z',
  },
  {
    id: 'inv_1043',
    organizationId: 'org_apex_studio',
    clientId: 'cli_novabuild',
    clientName: 'Vikram Mehta',
    clientEmail: 'vmehta@novabuild.in',
    companyName: 'NovaBuild Infra',
    invoiceNumber: 'INV-1043',
    invoiceAmount: 101000,
    currency: 'INR',
    invoiceDate: '2026-08-01',
    dueDate: '2026-08-18',
    status: 'REMINDER_2',
    daysOverdue: 14,
    source: 'GOOGLE_SHEETS',
    sourceReference: 'row_14_sheet_invoices',
    lastReminderAt: '2026-08-29T10:00:00Z',
    reminderCount: 2,
    nextReminderAt: '2026-09-04T10:00:00Z',
    isPaused: false,
    extractionConfidence: 'HIGH',
    notes: 'Infra portal UI design system milestone 3.',
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-08-29T10:00:00Z',
  },
  {
    id: 'inv_1044',
    organizationId: 'org_apex_studio',
    clientId: 'cli_zenith_media',
    clientName: 'Priya Mehra',
    clientEmail: 'priya@zenithmedia.agency',
    companyName: 'Zenith Growth Media',
    invoiceNumber: 'INV-1044',
    invoiceAmount: 100000,
    currency: 'INR',
    invoiceDate: '2026-08-20',
    dueDate: '2026-09-04',
    status: 'DUE',
    daysOverdue: 0,
    source: 'GMAIL',
    sourceReference: 'msg_gmail_9823479234',
    reminderCount: 0,
    nextReminderAt: '2026-09-07T10:00:00Z',
    isPaused: false,
    extractionConfidence: 'HIGH',
    notes: 'Monthly agency creative retainer - August 2026.',
    createdAt: '2026-08-20T11:00:00Z',
    updatedAt: '2026-08-20T11:00:00Z',
  },
  {
    id: 'inv_1045',
    organizationId: 'org_apex_studio',
    clientId: 'cli_craft_roasters',
    clientName: 'Devika Rao',
    clientEmail: 'devika@craftroasters.co',
    companyName: 'Craft Coffee Roasters',
    invoiceNumber: 'INV-1045',
    invoiceAmount: 45000,
    currency: 'INR',
    invoiceDate: '2026-08-15',
    dueDate: '2026-08-30',
    status: 'OVERDUE',
    daysOverdue: 2,
    source: 'GOOGLE_SHEETS',
    sourceReference: 'row_16_sheet_invoices',
    reminderCount: 0,
    nextReminderAt: '2026-09-02T10:00:00Z',
    isPaused: false,
    extractionConfidence: 'HIGH',
    notes: 'Specialty coffee packaging design initial milestone.',
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-30T10:00:00Z',
  },
  {
    id: 'inv_1046',
    organizationId: 'org_apex_studio',
    clientId: 'cli_pulse_health',
    clientName: 'Dr. Sameer Joshi',
    clientEmail: 's.joshi@pulsehealth.org',
    companyName: 'Pulse Digital Healthcare',
    invoiceNumber: 'INV-1046',
    invoiceAmount: 160000,
    currency: 'INR',
    invoiceDate: '2026-08-25',
    dueDate: '2026-09-09',
    status: 'DUE',
    daysOverdue: 0,
    source: 'GMAIL',
    reminderCount: 0,
    nextReminderAt: '2026-09-12T10:00:00Z',
    isPaused: false,
    extractionConfidence: 'HIGH',
    notes: 'Telehealth dashboard redesign.',
    createdAt: '2026-08-25T14:00:00Z',
    updatedAt: '2026-08-25T14:00:00Z',
  },
  {
    id: 'inv_1038',
    organizationId: 'org_apex_studio',
    clientId: 'cli_abc_interiors',
    clientName: 'Rohit Sharma',
    clientEmail: 'rohit@abcinteriors.co',
    companyName: 'ABC Interiors & Architecture',
    invoiceNumber: 'INV-1038',
    invoiceAmount: 140000,
    currency: 'INR',
    invoiceDate: '2026-07-10',
    dueDate: '2026-07-25',
    status: 'PAID',
    daysOverdue: 0,
    source: 'GMAIL',
    reminderCount: 2,
    lastReminderAt: '2026-08-01T10:00:00Z',
    paymentReceivedAt: '2026-08-03T15:45:00Z',
    isPaused: false,
    extractionConfidence: 'HIGH',
    notes: 'Paid after Reminder #2. Reminders stopped automatically.',
    createdAt: '2026-07-10T10:00:00Z',
    updatedAt: '2026-08-03T15:45:00Z',
  },
  {
    id: 'inv_1039',
    organizationId: 'org_apex_studio',
    clientId: 'cli_zenith_media',
    clientName: 'Priya Mehra',
    clientEmail: 'priya@zenithmedia.agency',
    companyName: 'Zenith Growth Media',
    invoiceNumber: 'INV-1039',
    invoiceAmount: 200000,
    currency: 'INR',
    invoiceDate: '2026-07-20',
    dueDate: '2026-08-04',
    status: 'PAID',
    daysOverdue: 0,
    source: 'GOOGLE_SHEETS',
    reminderCount: 1,
    lastReminderAt: '2026-08-07T10:00:00Z',
    paymentReceivedAt: '2026-08-08T11:20:00Z',
    isPaused: false,
    extractionConfidence: 'HIGH',
    notes: 'Paid after Reminder #1.',
    createdAt: '2026-07-20T10:00:00Z',
    updatedAt: '2026-08-08T11:20:00Z',
  },
];

export const INITIAL_REMINDERS: Reminder[] = [
  {
    id: 'rem_1042_2',
    organizationId: 'org_apex_studio',
    invoiceId: 'inv_1042',
    clientId: 'cli_abc_interiors',
    sequenceNumber: 2,
    scheduledAt: '2026-09-02T10:00:00Z',
    status: 'PENDING_APPROVAL',
    tone: 'PROFESSIONAL',
    subject: 'Following up: Invoice #INV-1042 (₹75,000) for ABC Interiors',
    body: `Hi Rohit,\n\nI hope you're having a good week.\n\nI am following up on Invoice #INV-1042 for ₹75,000 which was due on 25 Aug 2026 (7 days ago).\n\nCould you please check with your finance department and confirm the expected date for this transfer?\n\nIf payment is already in transit, please feel free to disregard this note.\n\nThank you,\nAnupam Saini\nApex Design & Tech Studio`,
    aiGenerated: true,
    approvedByUser: false,
    requiresReview: true,
    createdAt: '2026-09-01T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'rem_1045_1',
    organizationId: 'org_apex_studio',
    invoiceId: 'inv_1045',
    clientId: 'cli_craft_roasters',
    sequenceNumber: 1,
    scheduledAt: '2026-09-02T10:00:00Z',
    status: 'PENDING_APPROVAL',
    tone: 'FRIENDLY',
    subject: 'Friendly note: Invoice #INV-1045 (₹45,000) from Apex Design',
    body: `Hi Devika,\n\nHope you're enjoying the brand new packaging concepts!\n\nThis is just a friendly check-in regarding Invoice #INV-1045 for ₹45,000, which reached its due date on 30 Aug 2026.\n\nPlease let us know if you need another copy of the invoice or banking coordinates.\n\nBest regards,\nAnupam Saini\nApex Design & Tech Studio`,
    aiGenerated: true,
    approvedByUser: false,
    requiresReview: true,
    createdAt: '2026-09-01T08:30:00Z',
    updatedAt: '2026-09-01T08:30:00Z',
  },
  {
    id: 'rem_1043_2',
    organizationId: 'org_apex_studio',
    invoiceId: 'inv_1043',
    clientId: 'cli_novabuild',
    sequenceNumber: 2,
    scheduledAt: '2026-08-29T10:00:00Z',
    sentAt: '2026-08-29T10:01:14Z',
    status: 'SENT',
    tone: 'FIRM',
    subject: 'Second Follow-up: Invoice #INV-1043 (₹1,01,000) - Overdue by 14 Days',
    body: `Dear Vikram,\n\nWe are following up regarding Invoice #INV-1043 for ₹1,01,000, which remains unpaid after the due date of 18 Aug 2026.\n\nPlease provide an update on when payment will be cleared, as this milestone is now 14 days overdue.\n\nThank you for your prompt attention.\n\nRegards,\nApex Accounts Team`,
    gmailMessageId: '18f2938a19bc304d',
    aiGenerated: true,
    approvedByUser: true,
    requiresReview: false,
    createdAt: '2026-08-28T16:00:00Z',
    updatedAt: '2026-08-29T10:01:14Z',
  },
];

export const INITIAL_EMAIL_EVENTS: EmailEvent[] = [
  {
    id: 'evt_01',
    organizationId: 'org_apex_studio',
    invoiceId: 'inv_1043',
    clientId: 'cli_novabuild',
    gmailMessageId: '18f2938a19bc304d',
    direction: 'OUTBOUND',
    eventType: 'REMINDER_SENT',
    subject: 'Second Follow-up: Invoice #INV-1043 (₹1,01,000) - Overdue by 14 Days',
    sender: 'sainianupam07@gmail.com',
    recipient: 'vmehta@novabuild.in',
    bodyPreview: 'Dear Vikram, We are following up regarding Invoice #INV-1043 for ₹1,01,000...',
    eventTimestamp: '2026-08-29T10:01:14Z',
    createdAt: '2026-08-29T10:01:14Z',
  },
  {
    id: 'evt_02',
    organizationId: 'org_apex_studio',
    invoiceId: 'inv_1042',
    clientId: 'cli_abc_interiors',
    gmailMessageId: '18e90a82b9c71e22',
    direction: 'OUTBOUND',
    eventType: 'REMINDER_SENT',
    subject: 'Friendly reminder: Invoice #INV-1042 from Apex Design',
    sender: 'sainianupam07@gmail.com',
    recipient: 'rohit@abcinteriors.co',
    bodyPreview: 'Hi Rohit, Hope you have a good week. Quick note regarding Invoice #INV-1042...',
    eventTimestamp: '2026-08-28T09:30:00Z',
    createdAt: '2026-08-28T09:30:00Z',
  },
  {
    id: 'evt_03',
    organizationId: 'org_apex_studio',
    invoiceId: 'inv_1038',
    clientId: 'cli_abc_interiors',
    gmailMessageId: '18d890bfa3829031',
    direction: 'INBOUND',
    eventType: 'PAYMENT_CONFIRMATION',
    subject: 'Re: Follow-up: Invoice #INV-1038 Payment Processed',
    sender: 'rohit@abcinteriors.co',
    recipient: 'sainianupam07@gmail.com',
    bodyPreview: 'Hi Anupam, RTGS transfer of ₹1,40,000 completed. UTR: HDFC9023849023.',
    eventTimestamp: '2026-08-03T15:40:00Z',
    createdAt: '2026-08-03T15:40:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud_01',
    organizationId: 'org_apex_studio',
    eventType: 'AI_REMINDER_GENERATED',
    entityType: 'REMINDER',
    entityId: 'rem_1042_2',
    message: 'AI generated Reminder #2 for Invoice #INV-1042 (Rohit Sharma - ABC Interiors). Placed in review queue.',
    createdAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'aud_02',
    organizationId: 'org_apex_studio',
    eventType: 'REMINDER_SENT',
    entityType: 'REMINDER',
    entityId: 'rem_1043_2',
    message: 'Sent Reminder #2 via Gmail to vmehta@novabuild.in for Invoice #INV-1043 (₹1,01,000).',
    createdAt: '2026-08-29T10:01:14Z',
  },
  {
    id: 'aud_03',
    organizationId: 'org_apex_studio',
    eventType: 'INVOICE_MARKED_PAID',
    entityType: 'INVOICE',
    entityId: 'inv_1038',
    message: 'Invoice #INV-1038 (₹1,40,000) marked as PAID. All future reminders stopped automatically.',
    createdAt: '2026-08-03T15:45:00Z',
  },
  {
    id: 'aud_04',
    organizationId: 'org_apex_studio',
    eventType: 'INVOICE_DETECTED',
    entityType: 'INVOICE',
    entityId: 'inv_1046',
    message: 'Detected new outgoing invoice email to s.joshi@pulsehealth.org. Normalized as #INV-1046.',
    createdAt: '2026-08-25T14:00:00Z',
  },
  {
    id: 'aud_05',
    organizationId: 'org_apex_studio',
    eventType: 'CONNECTION_ESTABLISHED',
    entityType: 'CONNECTION',
    entityId: 'conn_gmail',
    message: 'Gmail OAuth connection verified for sainianupam07@gmail.com with send & read scopes.',
    createdAt: '2026-07-01T10:05:00Z',
  },
];

export const INITIAL_CONNECTIONS: Connection[] = [
  {
    id: 'conn_gmail',
    organizationId: 'org_apex_studio',
    provider: 'GMAIL',
    status: 'CONNECTED',
    accountIdentifier: 'sainianupam07@gmail.com',
    scopes: [
      'https://www.googleapis.com/auth/gmail.readonly',
      'https://www.googleapis.com/auth/gmail.send',
    ],
    lastSyncAt: '2026-09-01T21:40:00Z',
    createdAt: '2026-07-01T10:05:00Z',
    updatedAt: '2026-09-01T21:40:00Z',
  },
  {
    id: 'conn_sheets',
    organizationId: 'org_apex_studio',
    provider: 'GOOGLE_SHEETS',
    status: 'CONNECTED',
    accountIdentifier: 'sainianupam07@gmail.com',
    scopes: ['https://www.googleapis.com/auth/spreadsheets.readonly'],
    lastSyncAt: '2026-09-01T21:30:00Z',
    createdAt: '2026-07-01T10:10:00Z',
    updatedAt: '2026-09-01T21:30:00Z',
    sheetMetadata: {
      spreadsheetId: '1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
      spreadsheetName: 'Apex_Studio_Invoices_FY26',
      sheetName: 'Active Invoices',
      columnMapping: {
        invoiceNumber: 'A',
        clientName: 'B',
        clientEmail: 'C',
        amount: 'D',
        currency: 'E',
        invoiceDate: 'F',
        dueDate: 'G',
        status: 'H',
        notes: 'I',
      },
    },
  },
];

export const INITIAL_AUTOMATION_SETTINGS: AutomationSettings = {
  id: 'auto_set_01',
  organizationId: 'org_apex_studio',
  automaticReminders: true,
  automaticallyStopWhenPaid: true,
  avoidWeekends: true,
  preferredSendingTime: '10:00',
  timezone: 'Asia/Kolkata',
  policyTier: 'STANDARD',
  policyIntervals: {
    firstReminderDays: 3,
    secondReminderDays: 10,
    finalReminderDays: 17,
  },
  maxReminders: 3,
};

export const INITIAL_AI_SETTINGS: AISettings = {
  id: 'ai_set_01',
  organizationId: 'org_apex_studio',
  communicationStyle: 'PROFESSIONAL',
  relationshipAwarePersonalization: true,
  reviewBeforeSending: true,
  customToneInstructions: 'Keep communications calm, courteous, and strictly professional. Never sound adversarial.',
};

export const INITIAL_SUBSCRIPTION: Subscription = {
  id: 'sub_pro_01',
  organizationId: 'org_apex_studio',
  plan: 'PROFESSIONAL',
  status: 'ACTIVE',
  currentPeriodStart: '2026-08-01T00:00:00Z',
  currentPeriodEnd: '2026-09-01T00:00:00Z',
  cancelAtPeriodEnd: false,
  limits: {
    activeInvoices: 100,
    remindersPerMonth: 500,
    gmailAccounts: 2,
    aiReminders: true,
    relationshipIntelligence: true,
    customRules: true,
    teamMembers: 5,
  },
};

export const INITIAL_USAGE: Usage = {
  organizationId: 'org_apex_studio',
  month: '2026-09',
  activeInvoicesCount: 5,
  remindersSentCount: 38,
  aiGenerationsCount: 42,
  connectedGmailAccounts: 1,
};

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_01',
    organizationId: 'org_apex_studio',
    type: 'ALERT',
    title: 'Reminder Ready for Review',
    message: 'Follow-up #2 for Invoice #INV-1042 (ABC Interiors) is prepared and awaiting your approval.',
    actionUrl: '/app/reminders',
    read: false,
    createdAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'notif_02',
    organizationId: 'org_apex_studio',
    type: 'SUCCESS',
    title: 'Payment Detected & Follow-ups Stopped',
    message: 'Invoice #INV-1038 (₹1,40,000) was marked paid. All pending follow-ups were cancelled automatically.',
    actionUrl: '/app/invoices/inv_1038',
    read: true,
    createdAt: '2026-08-03T15:45:00Z',
  },
];

// Local Storage Helper Functions
export function loadFromStorage<T>(key: string, defaultValue: T): T {
  try {
    const item = localStorage.getItem(key);
    if (!item) return defaultValue;
    return JSON.parse(item);
  } catch {
    return defaultValue;
  }
}

export function saveToStorage<T>(key: string, value: T): void {
  try {
    localStorage.setItem(key, JSON.stringify(value));
  } catch (e) {
    console.error(`Failed to save to localStorage key ${key}`, e);
  }
}
